package assertion;

import action.ElementOperations;
import action.FindElementBasics;
import arrange.DriverWait;
import arrange.OpenCloseSite;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.BrowserType;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import static org.testng.Assert.*;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 05.04.2018 2018
 */
public class ElementOperationsTest extends ElementOperations {
    WebDriver webDriver;

    @BeforeMethod
    public void setUp() {
        webDriver = OpenCloseSite.openSiteByUrlBrowser("http://www.google.at", BrowserType.CHROME);
        DriverWait.waitForSecondsTimeOut(10, webDriver);
        webDriver.manage().window().maximize();
    }


    @Test
    public void testSetText() {
    }

    @Test
    public void testClick() {
    }

    @Test
    public void testGetParameter() {
        assertTrue("gb_2".equals(ElementOperations.getParameter(webDriver.findElement(By.cssSelector("#gb31 > span.gb_2")), "class") ));
    }

    @Test
    public void testGetText() {
        assertTrue("Bilder".equals(ElementOperations.getText(FindElementBasics.findByXPath
                (webDriver,"//a[@class='gb_P'][@data-pid='2']"))));
    }

    @AfterMethod
    public void tearDown() throws InterruptedException {
        Thread.sleep(1000);
        webDriver.close();
    }
}