package assertion;

import action.GetOptionsDropdown;
import arrange.DriverWait;
import arrange.OpenCloseSite;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.BrowserType;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import static org.testng.Assert.*;

/**
 * Package: action
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 06.04.2018 2018
 */
public class GetOptionsDropdownTest extends GetOptionsDropdown {

    Logger logger = Logger.getLogger("");
    WebDriver webDriver;
    WebElement languageDropdow;

    @BeforeMethod
    public void setUp() {
        webDriver = OpenCloseSite.openSiteByUrlBrowser("https://www.wikipedia.org/", BrowserType.CHROME);
        DriverWait.waitForSecondsTimeOut(10, webDriver);
        webDriver.manage().window().maximize();
    }

    @Test
    public void testGetOptions() {
        assertTrue("language".equals(webDriver.findElement(By.id("searchLanguage")).getAttribute("name")));
        List<WebElement> webElementList = GetOptionsDropdown.getOptions(webDriver.findElement(By.id("searchLanguage")));
        for (WebElement webElement : webElementList) {
            if ("da".equals(webElement.getAttribute("value"))) {
                webElement.click();
                assertTrue(webElement.isSelected());
                break;
            }

        }

    }

    @Test
    public void testGetParameterList() {
        List<String> list = GetOptionsDropdown.getParameterList(GetOptionsDropdown.getOptions(webDriver.findElement(By.id("searchLanguage"))));
        assertTrue(list.contains("vi"));
        assertFalse(list.contains("vietnam"));

    }

    @AfterMethod
    public void tearDown() throws InterruptedException {
        Thread.sleep(2000);
        logger.setLevel(Level.FINE);
        logger.info("Language list");
        webDriver.close();
    }
}