package assertion;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 02.04.2018 2018
 */
class OpenCloseSiteTest {

    @org.junit.jupiter.api.BeforeEach
    void setUp() {
    }

    @org.junit.jupiter.api.AfterEach
    void tearDown() {
    }

    @org.junit.jupiter.api.Test
    void openSiteByUrl() {
    }

    @org.junit.jupiter.api.Test
    void openSiteByUrlBrowser() {
    }

    @org.junit.jupiter.api.Test
    void closeSite() {
    }


}