package assertion;

import arrange.OpenCloseSite;
import org.testng.annotations.Test;

import static org.testng.Assert.*;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 02.04.2018 2018
 */
public class OpenCloseSiteTestNG extends OpenCloseSite {

    @org.testng.annotations.BeforeMethod
    public void setUp() {
    }

    @org.testng.annotations.AfterMethod
    public void tearDown() {
    }

    @org.testng.annotations.Test
    public void testOpenSiteByUrl() {
    }
}