package assertion;

import action.FindElementBasics;
import arrange.DriverWait;
import arrange.OpenCloseSite;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.BrowserType;
import org.testng.Assert;
import org.testng.annotations.Test;

import static org.testng.Assert.*;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 02.04.2018 2018
 */
public class OpenCloseSiteTestNG extends OpenCloseSite {
    WebDriver webDriver;

    @org.testng.annotations.BeforeMethod
    public void setUp() {
        webDriver = OpenCloseSite.openSiteByUrlBrowser("http://www.google.at", BrowserType.CHROME);
        DriverWait.waitForSecondsTimeOut(10, webDriver);
        webDriver.manage().window().maximize();
    }


    @org.testng.annotations.Test
    public void testOpenSiteByUrl() {
        assertTrue(FindElementBasics.findById(webDriver, "lst-ib").getAttribute("name").equals("q"));
    }

    @org.testng.annotations.Test
    void openSiteByUrlBrowser() {
        FindElementBasics.findByXPath(webDriver, "//*[@id='hplogo']");
    }
    @Test
    void getUrl(){
        assertTrue(("https://www.google.at/?gws_rd=ssl".equals(webDriver.getCurrentUrl())));
    }
    @Test
    void getTitle(){
        assertTrue("Google".equals(webDriver.getTitle()));
    }

    @Test
    void navigation(){
        webDriver.navigate().to("https://mail.google.com/mail/u/0/?tab=wm#inbox");
        assertTrue(("https://www.google.com/intl/de/gmail/about/#".equals(webDriver.getCurrentUrl())));
        webDriver.navigate().back();
        assertTrue(("https://www.google.at/?gws_rd=ssl".equals(webDriver.getCurrentUrl())));
        webDriver.navigate().forward();
        assertTrue(("https://www.google.com/intl/de/gmail/about/#".equals(webDriver.getCurrentUrl())));
    }

    @org.testng.annotations.AfterMethod
    public void tearDown() throws InterruptedException {
        Thread.sleep(1000);
        webDriver.close();
    }
}