package assertion;

import action.ElementOperations;
import action.FindElementBasics;
import arrange.OpenCloseSite;
import arrange.Wait;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.BrowserType;

import java.util.concurrent.TimeUnit;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 31.03.2018 2018
 */
public class SeleniumMain {
    public static void main(String[] args) {

        WebDriver webDriver = OpenCloseSite.openSiteByUrlBrowser("http://www.google.at", BrowserType.CHROME);
        //ElementOperations.setText(FindElementBasics.findById(webDriver, "lst-ib"), "anecon");
        //ElementOperations.setText(FindElementBasics.findByXPath(webDriver, "//*[@name='q']"), "anecon");
        ElementOperations.setText(FindElementBasics.findByName(webDriver, "q"), "anecon");
        //ElementOperations.click(FindElementBasics.findByLinkText(webDriver, "Gmail"));
        //ElementOperations.click(FindElementBasics.findByLinkPartialText(webDriver, "Über Google"));
        //ElementOperations.click(FindElementBasics.findByXPath(webDriver, "//input[@class='lsb'][@value='Auf gut Glück!']"));
        //ElementOperations.click(FindElementBasics.findByXPath(webDriver, "//*[@id='fsl']/a[1]"));
        //ElementOperations.click(FindElementBasics.findByXPath(webDriver, "//a[text()='Bilder']"));
        //ElementOperations.click(FindElementBasics.findByXPath(webDriver, "//a[contains(text(),'Bilder')]"));
        //ElementOperations.click(FindElementBasics.findByXPath(webDriver, "//*[@class ='gb_3f gb_Fa gb_Jb' and contains(text(),'An')]"));
        ElementOperations.click(FindElementBasics.findByXPath(webDriver, "//a[@href='https://www.google.at/intl/de/options/'and@title='Google-Apps']"));
        try {
            Wait.waitForSeconds(2);
        } catch (InterruptedException e) {

        }
        //ElementOperations.click(FindElementBasics.findByXPath(webDriver, "//*[@id='gb5']/span[1]"));
        ElementOperations.click(FindElementBasics.findByXPath(webDriver, "//a[starts-with(text(),'Mehr')]"));
        try {
            Wait.waitForSeconds(2);
        } catch (InterruptedException e) {

        }
        ElementOperations.click(FindElementBasics.findByXPath(webDriver, "//*[@id='gb136']/span[2]"));


        try {
            Wait.waitForSeconds(3);
        } catch (InterruptedException e) {

        }
        OpenCloseSite.closeSite();
    }
}
