package assertion;

import action.ElementOperations;
import action.FindElementBasics;
import action.SelectDopDown;
import arrange.DriverWait;
import arrange.OpenCloseSite;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.BrowserType;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.logging.Level;
import java.util.logging.Logger;

import static org.testng.Assert.*;

/**
 * Package: assertion
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 06.04.2018 2018
 */
public class SelectDropdownTest {
    Logger logger = Logger.getLogger("");
    WebDriver webDriver;
    WebElement languageDropdow;

    @BeforeMethod
    public void setUp() {
        webDriver = OpenCloseSite.openSiteByUrlBrowser("https://www.wikipedia.org/", BrowserType.CHROME);
        DriverWait.waitForSecondsTimeOut(10, webDriver);
        webDriver.manage().window().maximize();
    }

    @Test
    public void selectFromDropdown() {
        //first select
        languageDropdow = webDriver.findElement(By.id("searchLanguage"));
        SelectDopDown.selectByIndex(languageDropdow,2);
        ElementOperations.click(webDriver.findElement(By.xpath("//*[@id='search-form']/fieldset/button/i")));
        assertTrue("Посещаване на началната страница".equals(FindElementBasics.findByXPath(webDriver, "//a[@class='mw-wiki-logo']").getAttribute("title")));
        webDriver.navigate().back();
        //second select
        languageDropdow = webDriver.findElement(By.id("searchLanguage"));
        SelectDopDown.selectByValue(languageDropdow,"vi");
        ElementOperations.click(webDriver.findElement(By.xpath("//*[@id='search-form']/fieldset/button/i")));
        assertTrue("Trang Chính".equals(FindElementBasics.findByXPath(webDriver, "//a[@class='mw-wiki-logo']").getAttribute("title")));
        webDriver.navigate().back();
        //third select
        languageDropdow = webDriver.findElement(By.id("searchLanguage"));
        SelectDopDown.selectByText(languageDropdow,"Polski");
        ElementOperations.click(webDriver.findElement(By.xpath("//*[@id='search-form']/fieldset/button/i")));
        assertTrue("Strona główna".equals(FindElementBasics.findByXPath(webDriver, "//a[@class='mw-wiki-logo']").getAttribute("title")));
        webDriver.navigate().back();
        logger.setLevel(Level.FINER);
        logger.info("i am back!");

    }

    @AfterMethod
    public void tearDown() throws InterruptedException {
        Thread.sleep(2000);
        webDriver.close();
    }
}
