package arrange;

import org.openqa.selenium.WebDriver;

import java.util.concurrent.TimeUnit;

/**
 * Package: arrange
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 04.04.2018 2018
 */
public class DriverWait {
    public static void waitForSecondsTimeOut(int second, WebDriver webDriver) {
        webDriver.manage().timeouts().implicitlyWait(second, TimeUnit.SECONDS);
    }

    public static void waitForMinutesTimeOut(int minutes, WebDriver webDriver) {
        webDriver.manage().timeouts().implicitlyWait(minutes, TimeUnit.MINUTES);
    }
}
