package arrange;

import java.util.concurrent.TimeUnit;

/**
 * Package: arrange
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 01.04.2018 2018
 */
public class Wait {
    public static void waitForSeconds(int secs) throws InterruptedException {
        TimeUnit.SECONDS.sleep(secs);
    }
    public static void waitForMinutes(int mins) throws InterruptedException {
        TimeUnit.MINUTES.sleep(mins);
    }
}
