package action;

import org.openqa.selenium.WebElement;

/**
 * Package: action
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 01.04.2018 2018
 */
public class ElementOperations {
    public static void setText(WebElement element, String text){
        element.sendKeys(text);
    }
    public static void click(WebElement element){
        element.click();
    }
    public static String getParameter(WebElement webElement, String parameter){
        return webElement.getAttribute(parameter);
    }
}
