package action;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

/**
 * Package: action
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 01.04.2018 2018
 */
public class FindElementBasics {
    public static WebElement findById(WebDriver webDriver, String id){
        WebElement webElement = webDriver.findElement(By.id(id));
        return webElement;
    }
    public static WebElement findByName(WebDriver webDriver, String name){
        WebElement webElement = webDriver.findElement(By.name(name));
        return webElement;
    }
    public static WebElement findByLinkText(WebDriver webDriver, String linkText){
        WebElement webElement = webDriver.findElement(By.linkText(linkText));
        return webElement;
    }
    public static WebElement findByLinkPartialText(WebDriver webDriver, String partLinkText){
        WebElement webElement = webDriver.findElement(By.partialLinkText(partLinkText));
        return webElement;
    }
    public static WebElement findByXPath(WebDriver webDriver, String xpath){
        WebElement webElement = webDriver.findElement(By.xpath(xpath));
        return webElement;
    }
}
