package action;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.Select;

import java.util.ArrayList;
import java.util.List;

/**
 * Package: action
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 06.04.2018 2018
 */
public class GetOptionsDropdown {
    public static List getOptions(WebElement webElement){
        Select selectList = new Select(webElement);
        List<WebElement> webElementList= selectList.getOptions();
        return webElementList;
    }

    public static List getParameterList(List<WebElement> webElementList){
        List<String> listParameter = new ArrayList<String>();
        for(WebElement element : webElementList){
            listParameter.add(element.getAttribute("value"));
            System.out.println(element.getAttribute("value"));
        }
        return listParameter;
    }
}
