package action;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.Select;

/**
 * Package: action
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 06.04.2018 2018
 */
public class SelectDopDown {
    public static void selectByIndex(WebElement webElement, int index){
        Select selectLanguage = new Select(webElement);
        selectLanguage.selectByIndex(index);
    }
    public static void selectByValue(WebElement webElement, String value){
        Select selectLanguage = new Select(webElement);
        selectLanguage.selectByValue(value);
    }
    public static void selectByText(WebElement webElement, String text){
        Select selectLanguage = new Select(webElement);
        selectLanguage.selectByVisibleText(text);
    }
}
